# Using load_iris for iris and genfromtxt for ionosphere.

In [170]:
from sklearn.datasets import load_iris
iris = load_iris()                #Loading Iris Dataset



In [171]:
import numpy as np
ionos = np.genfromtxt("ionosphere.txt",delimiter=",") #loading Ionosphere using genfromtext for converting into values
type(ionos)

numpy.ndarray

 Splitting the dataset into the training and test sets. using the function
train_test_split in scikit-learn, in which case use your birthday in
the format DDMM as random_state (omit leading zeros if any).

In [172]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(iris['data'],iris['target'], test_size=0.2, random_state=2805) 
                                                      #random state=DDMM(Birthdate) is for getting same output in multiple runs
print(y_train)
print(y_test)

[2 1 1 1 1 1 0 2 2 1 1 2 0 2 2 2 2 0 1 1 0 2 0 1 2 2 0 0 1 1 0 2 0 0 2 2 2
 2 0 1 2 0 2 1 2 0 1 0 1 0 1 1 2 2 1 0 1 2 1 2 0 0 2 0 2 2 0 1 2 1 2 0 0 0
 2 0 0 1 0 2 1 0 2 0 1 1 1 1 0 1 1 0 2 1 0 1 1 0 1 2 2 2 1 2 0 1 2 1 2 2 1
 2 1 0 0 2 0 0 1 2]
[0 0 1 1 1 2 0 0 1 1 1 0 0 2 0 1 1 2 0 0 0 2 2 0 1 2 0 2 0 2]


In [173]:
import pandas as pd
ion = pd.DataFrame(ionos) #DataFrame is used as a Two-Dimensional tabular data structure with labelled axes(rows,columns) 
                            #so that iloc function can access the index values from dataset.
ion.head()
x1 = ion.iloc[:,:-1].values
y1=ion.iloc[:,-1].values
print(x1.shape)
print(y1.shape)
x1_train,x1_test,y1_train,y1_test = train_test_split(x1,y1, test_size=0.2, random_state=2805) 
print(x1_train)
print(x1_test)

(351, 34)
(351,)
[[ 1.       0.       1.      ... -0.89093  0.22995 -0.89158]
 [ 1.       0.       0.8471  ... -0.06678  0.85764 -0.06151]
 [ 1.       0.       0.76296 ... -0.27105  1.      -0.57037]
 ...
 [ 0.       0.       1.      ...  1.       0.       0.     ]
 [ 1.       0.       0.8811  ...  0.05488  0.97561 -0.0122 ]
 [ 1.       0.       0.95882 ... -0.10797  0.93144 -0.06888]]
[[ 0.       0.       0.      ...  1.       0.       0.     ]
 [ 1.       0.       0.95659 ... -0.39061  0.82166 -0.41173]
 [ 1.       0.       1.      ...  1.       1.       1.     ]
 ...
 [ 1.       0.       0.      ...  0.       0.       0.     ]
 [ 1.       0.       0.4987  ... -0.05455  0.58961 -0.08571]
 [ 0.       0.       1.      ...  0.       1.      -1.     ]]


Implement the Nearest Neighbour method (i.e., the 1 Nearest Neighbours
method). Run it on both datasets: train it on the training set and compute
the number of errors it makes on the test set and the test error rate (the
ratio of the number of errors to the size of the test set).

In [174]:
import math
import numpy as np
def Euclidean_Dist(x_train, x_test): 
    sum = 0
    for i in range(len(x_train)):        #Accepting all the elements in x_train using len function
        diff = x_test[i] - x_train[i]    #for calculating distance between test samples and train samples  
        sum = sum + (diff * diff)
        d = np.sqrt(sum)    
    return d

In [175]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)# to implement for 3 nearest neighbor

def predict(x_train,x_test,y_train): #general function for implementation of nearest neighbor
    labels = []    #for storing prediction labels
    distances = [] #for storing distances
    for i in range(len(x_test)):                         
        for j in range(len(x_train)):
            cal_dist = Euclidean_Dist(x_train[j],x_test[i])
            distances.append(cal_dist)                       #storing the element of  calculated distances using append 
        minIndex=distances.index(min(distances))
        a=y_train[minIndex]                         
        labels.append(a)          #for aSppending predicted labels into array
        distances.clear()         #For flushing the array
        
    return labels
knn.fit(x_train,y_train)
y = knn.score(x_test,y_test) #knn for Iris Data Set
print("Iris Data Accuracy for K=3: ",y)
k_error_rate = print("Error Rate for", 1 - y) 

Iris Data Accuracy for K=3:  0.9333333333333333
Error Rate for 0.06666666666666665


In [176]:
knn.fit(x1_train,y1_train)
knn.predict(x1_test)
a = knn.score(x1_test,y1_test) #knn for Ionosphere Data Set
print("Ionosphere data Accuracy for K=3: ",a)
k_error_rate = print("Error Rate for", 1 - a) 

Ionosphere data Accuracy for K=3:  0.8450704225352113
Error Rate for 0.15492957746478875


In [177]:
y_pred = predict(x_train,x_test,y_train) 
Accuracy_IRIS = np.mean(y_pred==y_test)  #Accuracy for Iris data for nn

no = 0
size =  y_test.shape[0]
for x in range(size):
    if(y_pred[x] != y_test[x]):      #to get error which are not similar
        no=no+1
print("Accuracy for IRIS :", Accuracy_IRIS)
print("No. of errors: ",no)                    
Error_rate_IRIS = 1 -  np.mean(y_pred==y_test)     #Error rate for Iris data
print("Error Rate:",Error_rate_IRIS)

Accuracy for IRIS : 0.9333333333333333
No. of errors:  2
Error Rate: 0.06666666666666665


In [178]:
y1_pred = predict(x1_train,x1_test,y1_train)
Accuracy_Ionos = np.mean(y1_pred == y1_test) #Accuracy for Ionosphere
no = 0
size =  y1_test.shape[0]
for x in range(size):
    if(y1_pred[x] != y1_test[x]):
        no=no+1
print("Accuracy for Ionosphere :", Accuracy_Ionos)
print("No. of errors: ",no)
Error_rate_IONOS = 1 - np.mean(y1_pred==y1_test)#Error Rate for Ionosphere Data
print("Error Rate: ",Error_rate_IONOS)

Accuracy for Ionosphere : 0.8450704225352113
No. of errors:  11
Error Rate:  0.15492957746478875
